CREATE TABLE IF NOT EXISTS page_events (
  id SERIAL PRIMARY KEY,
  type_event TEXT,
  ga_id TEXT,
  user_id TEXT,
  item_id TEXT,
  item_type TEXT,
  page_ref TEXT,
  tags TEXT,
  add_cart_item_ids TEXT,
  add_coment_comment TEXT,
  carr_img_display_img_ref TEXT,
  carr_img_display_pos INTEGER,
  carr_img_view_img_ref TEXT,
  carr_img_view_pos INTEGER,
  category_click_category TEXT,
  index_search_category TEXT,
  index_search_search TEXT,
  page_search_search TEXT,
  page_search_filter TEXT,
  item_display_pos TEXT,
  item_view_pos TEXT,
  item_rtime_time INTEGER,
  event_time TIMESTAMP,
  event_ingest TIMESTAMP,
  data JSONB,
  item_click_title TEXT,
  carr_click TEXT,
  contact TEXT
);
